baseURL = 'http://darling.blog.br/'
copyright = 'Renan Dev'
defaultContentLanguageInSubdir = true
languageCode = 'pt-br'
title = 'Darling'

DefaultContentLanguage = "pt"
[params]
  site_logo = '/uploads/logo.png'
  commento_enable= true
show_reading_time=true
[languages]
[languages.pt]
languageName = "Portugues"
title = 'Darling - Blog de relacionamento'
weight = 1
[languages.en]
languageName = "English"
title = "Darling"
weight = 2
