---
label: default
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: list
  name: tags
  label: tags
- type: text
  name: featured_image
  label: featured_image
- type: text
  name: description
  label: description
pages:
- content/posts/primeiro-dia-dos-namorados.md
